image: haskell:8.8.4

variables:
  STACK_ROOT: "${CI_PROJECT_DIR}/.stack"

cache:
  paths:
    - .apt
    - .stack
    - .stack-work
    - target

before_script:
  - rm -f /etc/apt/apt.conf.d/docker-clean
  - mkdir -p .apt
  - rm -rf /var/cache/apt
  - mkdir -p /var/cache/apt
  - mount --bind .apt /var/cache/apt
  - apt-get update -yqq
  - apt-get install -y --no-install-recommends graphviz dot2tex libtinfo5 texlive-latex-base poppler-utils preview-latex-style texlive-pstricks
  - stack config set system-ghc --global true

build:
  stage: build
  script:
    - stack build
  after_script:
    - mv .stack-work/install/*/*/*/bin ./bin
  artifacts:
    paths:
      - "bin/"

test:
  stage: test
  script:
    - stack --no-terminal test --coverage
  after_script:
    - mv .stack-work/install/*/*/*/hpc ./hpc
  artifacts:
    paths:
      - "hpc/"

bench-build:
  stage: build
  needs:
    - build
  script:
    - stack --no-terminal bench --no-run-benchmarks

hlint:
  stage: build
  needs:
    - build
  script:
    - curl -sL https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh | sh -s .
