resolver: lts-10.4

packages:
- '.'
- location:
    git: https://github.com/m4lvin/cudd.git
    commit: cc794dd2c7d9f6b6cc9560226a4fb9cbe5c4454c
  extra-dep: true
- location:
    git: https://github.com/m4lvin/HasCacBDD.git
    commit: 23405da09876356569fbbb4f150e33199e5546f9
  extra-dep: true
