resolver: lts-12.18

packages:
- '.'

extra-deps:
- git: https://github.com/m4lvin/cudd.git
  commit: 32f7d6b764a80bbf8f84c07e2c1d691469aaaba0
- git: https://github.com/m4lvin/HasCacBDD.git
  commit: 29a40f1a94b2b9579c5c3bfb9f4df9038ba1ff65
